// 1. BỘ SƯU TẬP 15+ CHỦ ĐỀ MINH HỌA (SPECIAL THEMES WITH PATTERNS & VIBES)
export const SPECIAL_THEMES = {
  // --- MẶC ĐỊNH ---
  DEFAULT: {
    id: "DEFAULT",
    name: "Mặc định (Messenger)",
    category: "classic",
    quickEmoji: "💬",
    headerBg: "bg-white dark:bg-zinc-900 border-b border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white",
    headerText: "text-zinc-900 dark:text-white",
    chatBg: "bg-slate-50 dark:bg-zinc-950",
    bodyBg: "bg-slate-50 dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-blue-600 to-indigo-600 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100 border border-slate-200 dark:border-zinc-700/60",
    theirBubble: "bg-white dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100 border border-slate-200 dark:border-zinc-700/60",
    accentColor: "#2563eb",
    previewDot: "bg-blue-600",
  },

  // --- TÌNH YÊU & LÃNG MẠN ---
  LOVE_ROSE: {
    id: "LOVE_ROSE",
    name: "Hoa Hồng Đỏ",
    category: "love",
    quickEmoji: "🌹",
    headerBg: "bg-gradient-to-r from-rose-600 to-red-600 text-white",
    headerText: "text-white",
    chatBg: "bg-rose-50/80 dark:bg-zinc-950",
    bodyBg: "bg-rose-50/80 dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-rose-500 to-red-600 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-rose-500 to-red-600 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-rose-950 dark:text-rose-200 border border-rose-200 dark:border-rose-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-rose-950 dark:text-rose-200 border border-rose-200 dark:border-rose-900/50",
    accentColor: "#e11d48",
    previewDot: "bg-rose-600",
  },
  SWEET_CANDY: {
    id: "SWEET_CANDY",
    name: "Kẹo Ngọt Trái Tim",
    category: "love",
    quickEmoji: "💖",
    headerBg: "bg-gradient-to-r from-pink-500 via-rose-500 to-red-500 text-white",
    headerText: "text-white",
    chatBg: "bg-[#fff0f3] dark:bg-zinc-950 bg-[radial-gradient(#fbcfe8_1px,transparent_1px)] [background-size:16px_16px]",
    bodyBg: "bg-[#fff0f3] dark:bg-zinc-950 bg-[radial-gradient(#fbcfe8_1px,transparent_1px)] [background-size:16px_16px]",
    sentBubble: "bg-gradient-to-r from-pink-500 to-rose-500 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-pink-500 to-rose-500 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-pink-950 dark:text-pink-200 border border-pink-200 dark:border-pink-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-pink-950 dark:text-pink-200 border border-pink-200 dark:border-pink-900/50",
    accentColor: "#f43f5e",
    previewDot: "bg-gradient-to-r from-pink-500 to-rose-500",
  },
  ROMANTIC_PURPLE: {
    id: "ROMANTIC_PURPLE",
    name: "Tím Thủy Chung",
    category: "love",
    quickEmoji: "💜",
    headerBg: "bg-gradient-to-r from-purple-600 to-pink-500 text-white",
    headerText: "text-white",
    chatBg: "bg-purple-50/70 dark:bg-zinc-950",
    bodyBg: "bg-purple-50/70 dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-purple-950 dark:text-purple-200 border border-purple-200 dark:border-purple-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-purple-950 dark:text-purple-200 border border-purple-200 dark:border-purple-900/50",
    accentColor: "#a855f7",
    previewDot: "bg-purple-600",
  },

  // --- DỄ THƯƠNG (CUTE / PASTEL) ---
  CUTE_CAT: {
    id: "CUTE_CAT",
    name: "Mèo Con Vàng",
    category: "cute",
    quickEmoji: "🐾",
    headerBg: "bg-gradient-to-r from-amber-400 to-orange-400 text-amber-950",
    headerText: "text-amber-950 font-bold",
    chatBg: "bg-[#fffbeb] dark:bg-zinc-950 bg-[radial-gradient(#fde68a_1.5px,transparent_1.5px)] [background-size:20px_20px]",
    bodyBg: "bg-[#fffbeb] dark:bg-zinc-950 bg-[radial-gradient(#fde68a_1.5px,transparent_1.5px)] [background-size:20px_20px]",
    sentBubble: "bg-gradient-to-r from-amber-400 to-orange-400 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-amber-400 to-orange-400 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-amber-950 dark:text-amber-200 border border-amber-200 dark:border-amber-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-amber-950 dark:text-amber-200 border border-amber-200 dark:border-amber-900/50",
    accentColor: "#f59e0b",
    previewDot: "bg-amber-400",
  },
  PEACH_BLOSSOM: {
    id: "PEACH_BLOSSOM",
    name: "Đào Tiên Pastel",
    category: "cute",
    quickEmoji: "🍑",
    headerBg: "bg-gradient-to-r from-orange-300 via-pink-300 to-rose-300 text-slate-800",
    headerText: "text-slate-800 font-bold",
    chatBg: "bg-[#fff7ed] dark:bg-zinc-950",
    bodyBg: "bg-[#fff7ed] dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-orange-400 to-rose-400 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-orange-400 to-rose-400 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-orange-950 dark:text-orange-200 border border-orange-200 dark:border-orange-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-orange-950 dark:text-orange-200 border border-orange-200 dark:border-orange-900/50",
    accentColor: "#fb923c",
    previewDot: "bg-rose-400",
  },
  MATCHA_BEAR: {
    id: "MATCHA_BEAR",
    name: "Gấu Trà Xanh",
    category: "cute",
    quickEmoji: "🍵",
    headerBg: "bg-gradient-to-r from-emerald-400 to-teal-400 text-emerald-950",
    headerText: "text-emerald-950 font-bold",
    chatBg: "bg-[#f0fdf4] dark:bg-zinc-950",
    bodyBg: "bg-[#f0fdf4] dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-emerald-400 to-teal-500 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-emerald-400 to-teal-500 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-emerald-950 dark:text-emerald-200 border border-emerald-200 dark:border-emerald-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-emerald-950 dark:text-emerald-200 border border-emerald-200 dark:border-emerald-900/50",
    accentColor: "#10b981",
    previewDot: "bg-emerald-500",
  },
  COTTON_CANDY: {
    id: "COTTON_CANDY",
    name: "Kẹo Bông Gòn",
    category: "cute",
    quickEmoji: "✨",
    headerBg: "bg-gradient-to-r from-purple-300 via-pink-300 to-sky-300 text-slate-800",
    headerText: "text-slate-800 font-bold",
    chatBg: "bg-gradient-to-br from-indigo-50/50 via-purple-50/50 to-pink-50/50 dark:bg-zinc-950",
    bodyBg: "bg-gradient-to-br from-indigo-50/50 via-purple-50/50 to-pink-50/50 dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-purple-400 to-pink-400 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-purple-400 to-pink-400 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-purple-950 dark:text-purple-200 border border-purple-100 dark:border-purple-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-purple-950 dark:text-purple-200 border border-purple-100 dark:border-purple-900/50",
    accentColor: "#c084fc",
    previewDot: "bg-purple-400",
  },

  // --- KHOA HỌC, VŨ TRỤ & CÔNG NGHỆ ---
  CYBERPUNK: {
    id: "CYBERPUNK",
    name: "Cyberpunk 2077",
    category: "science",
    quickEmoji: "⚡",
    headerBg: "bg-slate-950 border-b border-cyan-500/30 text-cyan-400",
    headerText: "text-cyan-400 font-bold",
    chatBg: "bg-[#0b0f19] bg-[linear-gradient(to_right,#1e293b15_1px,transparent_1px),linear-gradient(to_bottom,#1e293b15_1px,transparent_1px)] [background-size:24px_24px]",
    bodyBg: "bg-[#0b0f19] bg-[linear-gradient(to_right,#1e293b15_1px,transparent_1px),linear-gradient(to_bottom,#1e293b15_1px,transparent_1px)] [background-size:24px_24px]",
    sentBubble: "bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-[0_0_10px_rgba(6,182,212,0.3)]",
    myBubble: "bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-[0_0_10px_rgba(6,182,212,0.3)]",
    receivedBubble: "bg-slate-900 text-cyan-100 border border-cyan-900/50",
    theirBubble: "bg-slate-900 text-cyan-100 border border-cyan-900/50",
    accentColor: "#06b6d4",
    previewDot: "bg-cyan-500",
  },
  DEEP_GALAXY: {
    id: "DEEP_GALAXY",
    name: "Thiên Hà Huyền Bí",
    category: "science",
    quickEmoji: "🪐",
    headerBg: "bg-gradient-to-r from-slate-900 via-indigo-950 to-purple-950 text-indigo-200 border-b border-indigo-900/40",
    headerText: "text-indigo-200",
    chatBg: "bg-slate-950 text-slate-100",
    bodyBg: "bg-slate-950 text-slate-100",
    sentBubble: "bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 text-white shadow-xs",
    receivedBubble: "bg-slate-800 text-slate-200 border border-slate-700",
    theirBubble: "bg-slate-800 text-slate-200 border border-slate-700",
    accentColor: "#818cf8",
    previewDot: "bg-indigo-600",
  },
  MATRIX_CODE: {
    id: "MATRIX_CODE",
    name: "Ma Trận Số",
    category: "science",
    quickEmoji: "💻",
    headerBg: "bg-black border-b border-green-500/40 text-green-400 font-mono",
    headerText: "text-green-400 font-mono",
    chatBg: "bg-[#051105]",
    bodyBg: "bg-[#051105]",
    sentBubble: "bg-green-600 text-black font-semibold shadow-xs",
    myBubble: "bg-green-600 text-black font-semibold shadow-xs",
    receivedBubble: "bg-black text-green-400 border border-green-800",
    theirBubble: "bg-black text-green-400 border border-green-800",
    accentColor: "#22c55e",
    previewDot: "bg-green-500",
  },
  SOLAR_SYSTEM: {
    id: "SOLAR_SYSTEM",
    name: "Hệ Mặt Trời",
    category: "science",
    quickEmoji: "☀️",
    headerBg: "bg-gradient-to-r from-amber-600 via-orange-600 to-slate-900 text-white",
    headerText: "text-white",
    chatBg: "bg-[#0f172a]",
    bodyBg: "bg-[#0f172a]",
    sentBubble: "bg-gradient-to-r from-amber-500 to-orange-500 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-amber-500 to-orange-500 text-white shadow-xs",
    receivedBubble: "bg-slate-800 text-amber-100 border border-slate-700",
    theirBubble: "bg-slate-800 text-amber-100 border border-slate-700",
    accentColor: "#f59e0b",
    previewDot: "bg-amber-500",
  },

  // --- THIÊN NHIÊN, GIẢI TRÍ & CHILL ---
  SUMMER_POOL: {
    id: "SUMMER_POOL",
    name: "Bể Bơi Mùa Hè",
    category: "chill",
    quickEmoji: "🏖️",
    headerBg: "bg-gradient-to-r from-sky-400 to-cyan-500 text-white",
    headerText: "text-white",
    chatBg: "bg-[#e0f2fe] dark:bg-zinc-950 bg-[radial-gradient(#bae6fd_2px,transparent_2px)] [background-size:24px_24px]",
    bodyBg: "bg-[#e0f2fe] dark:bg-zinc-950 bg-[radial-gradient(#bae6fd_2px,transparent_2px)] [background-size:24px_24px]",
    sentBubble: "bg-sky-500 text-white shadow-xs",
    myBubble: "bg-sky-500 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-sky-950 dark:text-sky-200 border border-sky-200 dark:border-sky-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-sky-950 dark:text-sky-200 border border-sky-200 dark:border-sky-900/50",
    accentColor: "#0ea5e9",
    previewDot: "bg-sky-400",
  },
  SUNSET_LOFI: {
    id: "SUNSET_LOFI",
    name: "Hoàng Hôn Lofi",
    category: "chill",
    quickEmoji: "🎧",
    headerBg: "bg-gradient-to-r from-amber-500 via-rose-500 to-purple-600 text-white",
    headerText: "text-white",
    chatBg: "bg-gradient-to-b from-amber-50/50 via-rose-50/50 to-purple-50/50 dark:bg-zinc-950",
    bodyBg: "bg-gradient-to-b from-amber-50/50 via-rose-50/50 to-purple-50/50 dark:bg-zinc-950",
    sentBubble: "bg-gradient-to-r from-rose-500 to-amber-500 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-rose-500 to-amber-500 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-slate-800 dark:text-slate-200 border border-rose-100 dark:border-rose-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-slate-800 dark:text-slate-200 border border-rose-100 dark:border-rose-900/50",
    accentColor: "#f43f5e",
    previewDot: "bg-rose-500",
  },
  RETRO_PIXEL: {
    id: "RETRO_PIXEL",
    name: "Game 8-Bit Retro",
    category: "chill",
    quickEmoji: "🎮",
    headerBg: "bg-indigo-900 text-indigo-100 border-b border-indigo-700",
    headerText: "text-indigo-100 font-mono",
    chatBg: "bg-[#1e1b4b]/10 dark:bg-zinc-950",
    bodyBg: "bg-[#1e1b4b]/10 dark:bg-zinc-950",
    sentBubble: "bg-indigo-600 text-white shadow-xs",
    myBubble: "bg-indigo-600 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-indigo-950 dark:text-indigo-200 border border-indigo-200 dark:border-indigo-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-indigo-950 dark:text-indigo-200 border border-indigo-200 dark:border-indigo-900/50",
    accentColor: "#4f46e5",
    previewDot: "bg-indigo-600",
  },
  DEEP_FOREST: {
    id: "DEEP_FOREST",
    name: "Rừng Thông Tây Bắc",
    category: "chill",
    quickEmoji: "🌲",
    headerBg: "bg-gradient-to-r from-emerald-800 to-green-900 text-emerald-100",
    headerText: "text-emerald-100",
    chatBg: "bg-[#f0fdf4] dark:bg-zinc-950",
    bodyBg: "bg-[#f0fdf4] dark:bg-zinc-950",
    sentBubble: "bg-emerald-700 text-white shadow-xs",
    myBubble: "bg-emerald-700 text-white shadow-xs",
    receivedBubble: "bg-white dark:bg-zinc-800 text-emerald-950 dark:text-emerald-200 border border-emerald-200 dark:border-emerald-900/50",
    theirBubble: "bg-white dark:bg-zinc-800 text-emerald-950 dark:text-emerald-200 border border-emerald-200 dark:border-emerald-900/50",
    accentColor: "#047857",
    previewDot: "bg-emerald-700",
  },
  AURORA_BOREALIS: {
    id: "AURORA_BOREALIS",
    name: "Cực Quang Bắc Cực",
    category: "chill",
    quickEmoji: "🌌",
    headerBg: "bg-gradient-to-r from-teal-500 via-indigo-600 to-purple-600 text-white",
    headerText: "text-white",
    chatBg: "bg-slate-900 text-slate-100",
    bodyBg: "bg-slate-900 text-slate-100",
    sentBubble: "bg-gradient-to-r from-teal-400 to-indigo-500 text-white shadow-xs",
    myBubble: "bg-gradient-to-r from-teal-400 to-indigo-500 text-white shadow-xs",
    receivedBubble: "bg-slate-800 text-teal-100 border border-teal-800",
    theirBubble: "bg-slate-800 text-teal-100 border border-teal-800",
    accentColor: "#14b8a6",
    previewDot: "bg-teal-500",
  },
};

// 2. BỘ SƯU TẬP 50 BẢNG MÀU GRADIENT VÀ ĐƠN SẮC CHUẨN MESSENGER (50 COLOR PRESETS)
export const BASE_GRADIENTS = [
  { id: "MESSENGER_BLUE", name: "Xanh Messenger", from: "#0084ff", to: "#00c6ff", emoji: "💬" },
  { id: "OCEAN_BREEZE", name: "Gió Biển Xanh", from: "#2b5876", to: "#4e4376", emoji: "🌊" },
  { id: "ROYAL_BLUE", name: "Xanh Hoàng Gia", from: "#1e3c72", to: "#2a5298", emoji: "👑" },
  { id: "NEON_GLOW", name: "Neon Phản Quang", from: "#00f2fe", to: "#4facfe", emoji: "💡" },
  { id: "MAGIC_PURPLE", name: "Tím Huyền Diệu", from: "#654ea3", to: "#eaafc8", emoji: "🔮" },
  { id: "DEEP_PURPLE", name: "Tím Đậm Đà", from: "#360033", to: "#0b8793", emoji: "🍇" },
  { id: "LAVENDER_DREAM", name: "Oải Hương Mộng Mơ", from: "#7f00ff", to: "#e100ff", emoji: "🪻" },
  { id: "PASSION_RED", name: "Đỏ Rực Cháy", from: "#e52d27", to: "#b31217", emoji: "🔥" },
  { id: "CORAL_PINK", name: "Hồng San Hô", from: "#ff416c", to: "#ff4b2b", emoji: "🪸" },
  { id: "SUNSET_ORANGE", name: "Cam Chiều Tà", from: "#f12711", to: "#f5af19", emoji: "🌅" },
  { id: "MANGO_TROPICAL", name: "Xoài Nhiệt Đới", from: "#ffe259", to: "#ffa751", emoji: "🥭" },
  { id: "EMERALD_WATER", name: "Ngọc Bích", from: "#348ac7", to: "#7474bf", emoji: "💎" },
  { id: "LUSH_GREEN", name: "Rừng Xanh Mướt", from: "#56ab2f", to: "#a8e063", emoji: "🍃" },
  { id: "MINT_FRESH", name: "Bạc Hà Tươi Mát", from: "#00b09b", to: "#96c93d", emoji: "🌿" },
  { id: "TEAL_LOVE", name: "Xanh Mòng Két", from: "#134e5e", to: "#71b280", emoji: "🦚" },
  { id: "GOLDEN_LUXURY", name: "Hoàng Kim Sang Trọng", from: "#bf953f", to: "#fcf6ba", emoji: "⭐" },
  { id: "MIDNIGHT_CITY", name: "Thành Phố Nửa Đêm", from: "#232526", to: "#414345", emoji: "🌃" },
  { id: "DARK_KNIGHT", name: "Hiệp Sĩ Bóng Đêm", from: "#000000", to: "#434343", emoji: "🦇" },
  { id: "CHERRY_BLOSSOM", name: "Hoa Anh Đào", from: "#fbc2eb", to: "#a6c1ee", emoji: "🌸" },
  { id: "AUTUMN_LEAF", name: "Lá Phong Mùa Thu", from: "#d31027", to: "#ea384d", emoji: "🍁" },
  { id: "DISCO_FEVER", name: "Ánh Đèn Sân Khấu", from: "#ff007f", to: "#7f00ff", emoji: "🪩" },
  { id: "CYAN_BLAST", name: "Sóng Lam Biển Sâu", from: "#1d976c", to: "#93f9b9", emoji: "🐬" },
  { id: "FIRE_FLAME", name: "Ngọn Lửa Ấm Áp", from: "#f857a6", to: "#ff5858", emoji: "🕯️" },
  { id: "SPACE_LIGHT", name: "Ánh Sao Băng", from: "#43cea2", to: "#185a9d", emoji: "🌠" },
  { id: "BERRY_SMOOTHIE", name: "Sinh Tố Dâu Rừng", from: "#8e2de2", to: "#4a00e0", emoji: "🍓" },
  { id: "CITRUS_BURST", name: "Chanh Tươi Sảng Khoái", from: "#fdc830", to: "#f37335", emoji: "🍋" },
  { id: "ICE_COLD", name: "Băng Tuyết Mùa Đông", from: "#c2e9fb", to: "#a1c4fd", emoji: "❄️" },
  { id: "VELVET_WINE", name: "Vang Đỏ Thượng Hạng", from: "#600036", to: "#9b003a", emoji: "🍷" },
  { id: "COFFEE_LATTE", name: "Cà Phê Sữa Đậm", from: "#4b3832", to: "#854442", emoji: "☕" },
  { id: "AQUA_SPLASH", name: "Bọt Nước Biển Xanh", from: "#13547a", to: "#80d0c7", emoji: "💦" },
  { id: "SHADOW_STEEL", name: "Kim Loại Bóng", from: "#8e9eab", to: "#eef2f3", emoji: "🛡️" },
  { id: "ROSE_GOLD", name: "Vàng Hồng Quý Tộc", from: "#eacda3", to: "#d6ae7b", emoji: "💍" },
  { id: "TROPICAL_BIRD", name: "Chim Nhiệt Đới", from: "#fc466b", to: "#3f5efb", emoji: "🦜" },
  { id: "DEEP_OCEAN", name: "Đại Dương Đáy Sâu", from: "#021b79", to: "#0575e6", emoji: "🐋" },
  { id: "LIME_SODA", name: "Soda Chanh Tươi", from: "#11998e", to: "#38ef7d", emoji: "🍹" },
  { id: "FLAMINGO", name: "Hồng Hạc", from: "#f7797d", to: "#FBD786", emoji: "🦩" },
  { id: "PEACOCK", name: "Khổng Tước", from: "#00c6ff", to: "#0072ff", emoji: "🦚" },
  { id: "BLUSH_RED", name: "Má Hồng E Thẹn", from: "#ee9ca7", to: "#ffdde1", emoji: "😊" },
  { id: "PURPLE_HAZE", name: "Màn Sương Khói Tím", from: "#9d50bb", to: "#6e48aa", emoji: "🌫️" },
  { id: "ELECTRIC_VIOLET", name: "Tím Điện Quang", from: "#4776e6", to: "#8e54e9", emoji: "⚡" },
  { id: "SUNNY_DAY", name: "Nắng Sớm Ban Mai", from: "#fceabb", to: "#f8b500", emoji: "🌻" },
  { id: "BLOODY_MARY", name: "Cocktail Đỏ Cay", from: "#ff512f", to: "#dd2476", emoji: "🍸" },
  { id: "JUNGLE_FEVER", name: "Rừng Rậm Nhiệt Đới", from: "#2980b9", to: "#2c3e50", emoji: "🌴" },
  { id: "COSMIC_DUST", name: "Bụi Vũ Trụ", from: "#ff00cc", to: "#333399", emoji: "💫" },
  { id: "SWEET_MORNING", name: "Bình Minh Tươi Sáng", from: "#ff5f6d", to: "#ffc371", emoji: "🌅" },
  { id: "DEEP_COBALT", name: "Lam Cô-ban", from: "#0052d4", to: "#4364f7", emoji: "💠" },
  { id: "AMETHYST_GEM", name: "Thạch Anh Tím", from: "#9b51e0", to: "#3498db", emoji: "🔮" },
  { id: "WARM_EMBER", name: "Than Hồng Ấm Áp", from: "#f09819", to: "#edde5d", emoji: "🔥" },
  { id: "TRANQUIL_TEAL", name: "Lam Tĩnh Lặng", from: "#16a085", to: "#f4d03f", emoji: "🧘" },
  { id: "PURE_MINIMAL_DARK", name: "Đen Tối Giản", from: "#18181b", to: "#27272a", emoji: "🖤" }
];

// Sinh tự động cấu hình theme đầy đủ cho 50 bảng màu gradient
export const COLOR_THEMES = BASE_GRADIENTS.reduce((acc, item) => {
  acc[item.id] = {
    id: item.id,
    name: item.name,
    category: "gradient",
    quickEmoji: item.emoji,
    headerBg: `bg-[linear-gradient(135deg,${item.from},${item.to})] text-white`,
    headerText: "text-white",
    chatBg: "bg-slate-50 dark:bg-zinc-950",
    bodyBg: "bg-slate-50 dark:bg-zinc-950",
    sentBubble: `bg-[linear-gradient(135deg,${item.from},${item.to})] text-white shadow-xs`,
    myBubble: `bg-[linear-gradient(135deg,${item.from},${item.to})] text-white shadow-xs`,
    receivedBubble: "bg-white dark:bg-zinc-800 text-slate-800 dark:text-slate-100 border border-slate-200 dark:border-zinc-700/60",
    theirBubble: "bg-white dark:bg-zinc-800 text-slate-800 dark:text-slate-100 border border-slate-200 dark:border-zinc-700/60",
    accentColor: item.from,
    previewDot: `bg-[linear-gradient(135deg,${item.from},${item.to})]`,
    gradientColors: [item.from, item.to],
  };
  return acc;
}, {});

// TỔNG HỢP TOÀN BỘ THEME CHO CHAT SYSTEM
export const ALL_CHAT_THEMES = {
  ...SPECIAL_THEMES,
  ...COLOR_THEMES,
};

export const CHAT_THEMES = ALL_CHAT_THEMES;
export const DEFAULT_THEME_ID = "DEFAULT";

// Helper lấy theme an toàn có fallback
export function getChatTheme(themeId) {
  if (!themeId) return SPECIAL_THEMES.DEFAULT;
  return ALL_CHAT_THEMES[themeId] || SPECIAL_THEMES.DEFAULT;
}
