export const CHAT_THEMES = {
  DEFAULT: {
    id: "DEFAULT",
    name: "Mặc định (Slate & Blue)",
    primaryColor: "bg-blue-600",
    headerBg: "bg-white dark:bg-zinc-900",
    headerText: "text-zinc-900 dark:text-white",
    bodyBg: "bg-slate-50 dark:bg-zinc-950",
    myBubble: "bg-blue-600 text-white",
    theirBubble: "bg-white dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100 border border-slate-200 dark:border-zinc-700/60",
    accentColor: "text-blue-600",
    previewDot: "bg-blue-500",
  },
  OCEAN_POOL: {
    id: "OCEAN_POOL",
    name: "Đại Dương Xanh (Ocean Pool)",
    primaryColor: "bg-cyan-600",
    headerBg: "bg-gradient-to-r from-cyan-900 via-blue-900 to-indigo-900",
    headerText: "text-white",
    bodyBg: "bg-gradient-to-b from-cyan-950/40 via-slate-900/30 to-blue-950/40 bg-cyan-950/20",
    myBubble: "bg-gradient-to-r from-cyan-500 to-blue-600 text-white shadow-sm",
    theirBubble: "bg-white/90 dark:bg-zinc-800/90 backdrop-blur-xs text-zinc-900 dark:text-zinc-100 border border-cyan-500/20",
    accentColor: "text-cyan-500",
    previewDot: "bg-gradient-to-r from-cyan-400 to-blue-600",
  },
  GALAXY_SUN: {
    id: "GALAXY_SUN",
    name: "Vũ Trụ Hoàng Hôn (Galaxy Sun)",
    primaryColor: "bg-purple-600",
    headerBg: "bg-gradient-to-r from-purple-900 via-fuchsia-900 to-pink-900",
    headerText: "text-white",
    bodyBg: "bg-gradient-to-b from-purple-950/30 via-slate-950/30 to-fuchsia-950/30",
    myBubble: "bg-gradient-to-r from-purple-600 to-pink-600 text-white shadow-sm",
    theirBubble: "bg-white/90 dark:bg-zinc-800/90 backdrop-blur-xs text-zinc-900 dark:text-zinc-100 border border-purple-500/20",
    accentColor: "text-purple-500",
    previewDot: "bg-gradient-to-r from-purple-500 to-pink-500",
  },
  NOTEBOOK_GRID: {
    id: "NOTEBOOK_GRID",
    name: "Sổ Tay Retro (Notebook Grid)",
    primaryColor: "bg-amber-600",
    headerBg: "bg-amber-100 dark:bg-amber-950/70 border-b border-amber-200 dark:border-amber-900/50",
    headerText: "text-amber-950 dark:text-amber-200",
    bodyBg: "bg-amber-50/70 dark:bg-zinc-950",
    myBubble: "bg-amber-600 text-white shadow-sm",
    theirBubble: "bg-white dark:bg-zinc-800 text-zinc-900 dark:text-zinc-100 border border-amber-200 dark:border-zinc-700",
    accentColor: "text-amber-600",
    previewDot: "bg-amber-500",
  },
  FOREST_EMERALD: {
    id: "FOREST_EMERALD",
    name: "Rừng Ngọc Lục Bảo (Forest Emerald)",
    primaryColor: "bg-emerald-600",
    headerBg: "bg-gradient-to-r from-emerald-900 via-teal-900 to-green-950",
    headerText: "text-white",
    bodyBg: "bg-gradient-to-b from-emerald-950/20 via-slate-900/10 to-teal-950/20",
    myBubble: "bg-gradient-to-r from-emerald-600 to-teal-600 text-white shadow-sm",
    theirBubble: "bg-white/90 dark:bg-zinc-800/90 backdrop-blur-xs text-zinc-900 dark:text-zinc-100 border border-emerald-500/20",
    accentColor: "text-emerald-500",
    previewDot: "bg-gradient-to-r from-emerald-500 to-teal-500",
  },
  SUNSET_GLOW: {
    id: "SUNSET_GLOW",
    name: "Ánh Hoàng Hôn (Sunset Glow)",
    primaryColor: "bg-rose-500",
    headerBg: "bg-gradient-to-r from-orange-600 via-rose-600 to-pink-600",
    headerText: "text-white",
    bodyBg: "bg-gradient-to-b from-orange-950/20 via-rose-950/10 to-pink-950/20",
    myBubble: "bg-gradient-to-r from-orange-500 to-rose-500 text-white shadow-sm",
    theirBubble: "bg-white/90 dark:bg-zinc-800/90 backdrop-blur-xs text-zinc-900 dark:text-zinc-100 border border-rose-500/20",
    accentColor: "text-rose-500",
    previewDot: "bg-gradient-to-r from-orange-400 to-rose-500",
  },
  MIDNIGHT_NEON: {
    id: "MIDNIGHT_NEON",
    name: "Bóng Đêm Neon (Midnight Neon)",
    primaryColor: "bg-zinc-800",
    headerBg: "bg-zinc-950 border-b border-zinc-800",
    headerText: "text-cyan-400 font-bold",
    bodyBg: "bg-black/95",
    myBubble: "bg-cyan-500 text-black font-medium shadow-cyan-500/20 shadow-md",
    theirBubble: "bg-zinc-900 text-zinc-100 border border-zinc-800",
    accentColor: "text-cyan-400",
    previewDot: "bg-gradient-to-r from-cyan-400 to-zinc-900",
  },
};

export const DEFAULT_THEME_ID = "DEFAULT";

export function getChatTheme(themeId) {
  if (!themeId) return CHAT_THEMES.DEFAULT;
  return CHAT_THEMES[themeId] || CHAT_THEMES.DEFAULT;
}
